# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='serviceInfo',
            fields=[
                ('service_id', models.IntegerField(default=0)),
                ('service_instance_id', models.CharField(default='access_instance_1', max_length=64, primary_key=True, serialize=False)),
                ('service_instance_password', models.CharField(max_length=32, null=True)),
                ('service_token', models.CharField(max_length=38, null=True)),
                ('service_addr', models.CharField(max_length=256, null=True)),
                ('service_application_id', models.IntegerField(null=True)),
                ('adaptor_addr', models.CharField(max_length=256, null=True)),
                ('adaptor_application_id', models.IntegerField(null=True)),
                ('instance_group_id', models.IntegerField(null=True)),
                ('flowrate_overload_threshold', models.IntegerField(null=True)),
            ],
        ),
    ]
